[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "npm run server"
  healthcheckPath = "/api/auth/me"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10